services:
  fastapi:
    build:
      context: ./RAGdio-backend
      dockerfile: Dockerfile
    container_name: rag_audio_backend
    ports:
      - "8000:8000"
    env_file:
      - ./RAGdio-backend/.env
    depends_on:
      qdrant:
        condition: service_healthy
    restart: always

  qdrant:
    build:
      context: ./qdrant
      dockerfile: qdrant.Dockerfile
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./rag-audio-frontend
      dockerfile: vite-dev.Dockerfile
    container_name: rag_audio_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./rag-audio-frontend/.env
    volumes:
      - ./rag-audio-frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api

volumes:
  qdrant_data:
